feat: add parameter to disable path encoding
imgix/imgix-rb pull request #124
Opened 2022-10-06 07:46 UTC by pypas

## Description
Adds a `disable_path_encoding` parameter to allow user to opt-out of path encoding (issue: https://github.com/imgix/imgix-rb/issues/117)

## Checklist

- [x] Read the [contributing guidelines](CONTRIBUTING.md).
- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [x] Update the readme (if applicable).
- [x] Update or add any necessary API documentation (if applicable)
- [x] All existing unit tests are still passing (if applicable).
- [x] Add new passing unit tests to cover the code introduced by your PR (if applicable).

2022-10-07 03:21 UTC, atlawrie approved these changes
Hi @pypas,
While this looks good at first, there's one or two things we want to double check. Nonetheless, thank you for your hard work!

2022-10-07 04:24 UTC, atlawrie requested changes
Hi @pypas - looking into it a little deeper, it looks like your changes broke some of our preexisting tests as is. While your revised tests do pass as intended, there's a concern that this might serve as a breaking change for current users. In this instance, it'd be ideal for a solution to this issue to be able to pass our current tests as is, in addition to any new ones you've written testing the new functionality.

2022-10-07 08:17 UTC, pypas commented
Hey @atlawrie , I've updated the code as not to break the preexisting test, let me know what you think!

2022-10-13 18:53 UTC, luqven requested changes
Hey @pypas,

This is looking great, awesome work.

I do think we need to enable this functionality for the srcsets as well. Do you think you could update this PR to include the `disable_path_encoding` option when `to_url` in invoked in [build_srcset_pairs](https://github.com/pypas/imgix-rb/blob/feat/optionally-disable-path-encoding/lib/imgix/path.rb#L213) and [build_dpr_srcset](https://github.com/pypas/imgix-rb/blob/feat/optionally-disable-path-encoding/lib/imgix/path.rb#L233)?

edit: I forgot to mention, we'll need tests for `disable_path_encoding` in the `to_srcset` specs as well.

2022-10-17 16:13 UTC, sherwinski commented on README.md
> +
Just  a heads up that you're missing a closing ` ``` ` here

2022-10-17 19:24 UTC, luqven requested changes
LGTM 👍🏼 great work, let's just add that closing "```" to the README. I've also left two small non-blocking comments, but feel free to ignore them.

Once that README change is done we should be ready to merge.

2022-10-17 19:24 UTC, luqven commented on lib/imgix/path.rb
> +      return "/" + path
Nit, but I think it's a little easier to read if we remove the nested conditionals here and use `elsif` instead.

```suggestion
      if options[:disable_path_encoding]
        return "/" + path
      # if path is being used as a proxy, encode the entire thing
      elsif /^https?/ =~ path
        return encode_URI_Component(path)
      else
        # otherwise, encode only specific characters
        return encode_URI(path)
      end
```

2022-10-17 19:24 UTC, luqven commented on test/units/srcset_test.rb
> +    def test_enable_path_encoding
Nit, feel free to ignore. Path encoding isn't "enabled" but rather "default" behavior.

```suggestion
    def test_encode_path_by_default
```

2022-10-18 12:06 UTC, pypas commented
Thanks for the suggestions @luqven and @sherwinski!

2022-10-18 16:34 UTC, luqven approved these changes
LGTM 👍🏼 , great work on this 👏🏼 

![yes-nice-gif](https://user-images.githubusercontent.com/16711614/196490057-ef0e2440-185e-4ce1-b5aa-2a13563a39ed.gif)

2022-10-18 16:35 UTC, merged